apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operix.fullname" . }}-config
  namespace: {{ include "operix.namespace" . }}
  labels:
    {{- include "operix.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | default "" | indent 4 }}
