{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operix.redisFullname" . }}
  namespace: {{ include "operix.namespace" . }}
  labels:
    {{- include "operix.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
  selector:
    {{- include "operix.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end -}}
